daintree/daintree/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('root.urls')),
    path('order', include('order.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

daintree/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [ 
    path('index/', views.index, name='index'),
    path('<int:pk>/return_item/', views.return_item, name='return_item'),

]

daintree/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'), 
]

daintree/order/models.py
from django.db import models
from django.conf import settings
from item.models import Item

class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='items', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(Item, through='OrderItem')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    paid_amount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='order_items', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=8, decimal_places=2)

daintree/dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from item.models import Item
from order.models import Order, OrderItem
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.

@login_required
def index(request):
    user_items = Item.objects.filter(created_by=request.user)
    orders = Order.objects.filter(user=request.user).prefetch_related('orderitem_set')  # Prefetch related items for performance
    status = request.user.status

    return render(request, 'dashboard/index.html', {
        'user_items': user_items,
        'status': status,
        'orders': orders,
    })


@login_required
@require_POST
def return_item(request, pk):
    order_item = get_object_or_404(OrderItem, id=pk, order__user=request.user)
    order_item.delete()
    messages.success(request, "Item returned successfully.")
    return redirect('dashboard:index')

daintree/dashboard/templates/dashboard/index.html
{% extends 'root/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        {% if status == "seller" %}
            <h2 class="mb-12 text-2xl text-center">My items</h2>

            <div class="grid grid-cols-3 gap-3">
                {% for item in user_items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{item.name}}</h2>
                                <p class="text-gray-500">Price: {{item.price}}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>

        {% else %}
            <h2 class="mb-12 text-2xl text-center">My Order History</h2>
            

            <div class="grid grid-cols-3 gap-3">
                {% for order in orders %}   
                    {% if order.orderitem_set.all %}                 
                        <div>
                            <div class="p-6 bg-white rounded-b-xl">
                                <p class="text-gray-500 mb-2"><strong>Order Date: {{ order.updated_at }}</strong></p>
                                <p class="text-gray-500 mb-2">Amount Paid: {{ order.paid_amount }}</p>
                                    
                                <p class="text-gray-500 mb-2"><strong>Items:</strong></p>
                                <ul>
                                    {% for order_item in order.orderitem_set.all %}

                                        <a href="{% url 'item:detail' order_item.item.id %}">

                                            <li class="text-gray-500 mb-4 hover:bg-gray-700">
                                                {{ order_item.item.name }} - Price: {{ order_item.price }} (Quantity: {{ order_item.quantity }})
                                                <form action="{% url 'dashboard:return_item' order_item.id %}" method="post" style="display: inline;">
                                                    {% csrf_token %}
                                                    <button type="submit" class="mr-1 mt-2  right-0 px-2 py-2 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Return Item</button>
                                                </form>
                                            </li>
                                        </a>

                                        
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}

            </div>

        {% endif %}

        
    </div>
    
{% endblock %}