daintree/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

daintree/daintree/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('root.urls')),
    path('order', include('order.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

daintree/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [ 
    path('index/', views.index, name='index'),
    path('<int:pk>/return_item/', views.return_item, name='return_item'),

]

daintree/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'), 
]

daintree/order/urls.py
from django.urls import path
from . import views

app_name = 'order'


urlpatterns = [
    path('<int:pk>/add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('<int:pk>/remove_from_cart/', views.remove_from_cart, name='remove_from_cart'),
    path('<int:pk>/update_item_quantity/', views.update_item_quantity, name='update_item_quantity'),
    path('cart/', views.view_cart, name='view_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('confirmation/', views.confirmation, name='confirmation')
]

daintree/root/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm


app_name = 'root'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='root/login.html',authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

daintree/root/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager

class CustomUser(AbstractUser):
    STATUS_CHOICES = [
        ('seller', 'Seller'),
        ('buyer', 'Buyer'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='buyer')

    # add additional fields here
    objects = CustomUserManager()

daintree/root/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):

    STATUS_CHOICES = [
        # ('', ''),
        ('buyer', 'Buyer'),
        ('seller', 'Seller'),
        
    ]

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1',  'password2', 'status')


    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    status = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.Select(attrs={
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

daintree/root/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm

# Create your views here.

def index(request):
    items = Item.objects.filter(is_sold=False, is_approved=True)
    # Fetch parent categories
    parent_categories = Category.objects.filter(parent__isnull=True)
    
    # Prepare categories with item counts
    categories_with_counts = []
    for category in parent_categories:
        # Sum item counts in all subcategories
        item_count = Item.objects.filter(category__parent=category, is_sold=False, is_approved=True).count()
        categories_with_counts.append((category, item_count))
    
    return render(request, 'root/index.html', {
        'categories_with_counts': categories_with_counts,
        'items': items,
    })


def contact(request):
    return render(request, 'root/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        
        if form.is_valid(): 
            form.save() 

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'root/signup.html', {
        'form': form
    })

daintree/root/templates/root/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>


        <title>{% block title %}{% endblock %} | DainTree</title>


    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b gray-200 bg-blue-500">
            <a href="/" class="text-xl font-semibold text-white rounded-xl">DAINTREE</a>
            
            <div class="space-x-6">
                <!-- Checkout -->
                <a href="{% url 'order:view_cart' %}" class="py-3 px-6 text-lg font-semibold bg-white text-white rounded-xl">&#128722</a> 
                <a href="{% url 'item:items' %}"  class="py-3 px-6 text-lg font-semibold bg-white bg-teal-500 rounded-xl hover:bg-teal-700">Search</a>
                
                <!-- Conditionally render the following links based on authentication status -->
                {% if request.user.is_authenticated %}

                    <a href="{% url 'item:new' %}" class="py-3 px-6 text-lg text-lg font-semibold bg-white rounded-xl hover:bg-teal-700">New item</a>

                    <a href="{% url 'conversation:inbox' %}" class="py-3 px-6 text-lg font-semibold bg-teal-500  rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="py-3 px-6 text-lg font-semibold bg-teal-500  rounded-xl hover:bg-teal-700">Dashboard</a>

                    <!-- Logout form/button -->
                    <form action="{% url 'root:logout' %}" method="post" class="inline">
                        {% csrf_token %}
                        <button class="py-3 px-6 text-lg font-semibold bg-teal-500  rounded-xl hover:bg-teal-700" type="submit">Logout</button>
                    </form>
                    
                {% else %}
                    <a href="{% url 'root:signup' %}" class="py-3 px-6 text-lg font-semibold bg-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'root:login' %}" class="py-3 px-6 text-lg font-semibold bg-white  rounded-xl hover:bg-teal-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="py-6 px-6 pd-6 {{ message.tags }} text-gray-500 mb-2"><strong>
                        {{ message }}
                    </strong>
                        
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        
        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Content to be added</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-blue-500 hover:text-blue-700">About</a></li>
                    <li><a href="{% url 'root:contact' %}" class="text-lg text-blue-500 hover:text-blue-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-blue-500 hover:text-blue-700">Privacy Policy</a></li>
                    <li><a href="#" class="text-lg text-blue-500 hover:text-blue-700">Terms of Use</a></li>
                </ul>
            </div>
        </footer>
    </body>

</html>

daintree/root/templates/root/contact.html
{% extends 'root/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

daintree/root/templates/root/index.html
{% extends 'root/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Inventory</h2>

         <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{item.name}}</h2>
                            <p class="text-gray-500">Price: {{item.price}}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-5 gap-5">
            {% for category, item_count in categories_with_counts %}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{category.name}}</h2>
                        <p class="text-gray-500">{{item_count}}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>

    </div>
    
{% endblock %}

daintree/root/templates/root/login.html
{% extends 'root/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
                
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>

    </form>
</div>
{% endblock %}

daintree/root/templates/root/signup.html
{% extends 'root/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label><br>
            {{ form.password2}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Status</label><br>
            {{ form.status}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
                
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>

    </form>
</div>
{% endblock %}