daintree/daintree/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('root.urls')),
    path('order', include('order.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

daintree/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'), 
]

daintree/order/urls.py
from django.urls import path
from . import views

app_name = 'order'


urlpatterns = [
    path('<int:pk>/add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('<int:pk>/remove_from_cart/', views.remove_from_cart, name='remove_from_cart'),
    path('<int:pk>/update_item_quantity/', views.update_item_quantity, name='update_item_quantity'),
    path('cart/', views.view_cart, name='view_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('confirmation/', views.confirmation, name='confirmation')
]

daintree/order/models.py
from django.db import models
from django.conf import settings
from item.models import Item

class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='items', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(Item, through='OrderItem')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    paid_amount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='order_items', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=8, decimal_places=2)

daintree/order/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Cart, CartItem, Order, OrderItem
from django.contrib.auth.decorators import login_required
from item.models import Item

# Create your views here.
@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    cart, _ = Cart.objects.get_or_create(user=request.user)
    cart_item, created = CartItem.objects.get_or_create(item=item, cart=cart)
    
    if not created:
        # If the item already exists in the cart, increment the quantity
        cart_item.quantity = 1
        cart_item.save()
    
    return redirect('item:detail', pk=item.id)


@login_required
def update_item_quantity(request, pk):
    if request.method == 'POST':
        quantity = request.POST.get('quantity')
        cart_item = get_object_or_404(CartItem, pk=pk, cart__user=request.user)
        cart_item.quantity = quantity
        cart_item.save()
    return redirect('order:view_cart')


@login_required
def remove_from_cart(request, pk):
    cart_item = get_object_or_404(CartItem, pk=pk, cart__user=request.user)
    cart_item.delete()
    return redirect('order:view_cart')


@login_required
def view_cart(request):
    cart, created = Cart.objects.get_or_create(user=request.user)
    return render(request, 'order/cart.html', {'cart': cart})


@login_required
def checkout(request):
    if request.method == 'POST':
        cart, created = Cart.objects.get_or_create(user=request.user)
        order = Order.objects.create(user=request.user)
        total_price = 0
        for cart_item in cart.items.all():
            total_price += cart_item.item.price * cart_item.quantity
            OrderItem.objects.create(
                order=order,
                item=cart_item.item,
                seller=cart_item.item.created_by,
                quantity=cart_item.quantity,
                price=cart_item.item.price
            )
            cart_item.delete() # Delete the cart item after adding to order

        order.paid_amount = total_price
        order.save()

        #delete the cart if it's no longer needed
        cart.delete()

        return redirect('order:confirmation')

    return render(request,'order/checkout.html')


def confirmation(request):
     return render(request, 'order/confirmation.html')

daintree/order/templates/order/cart.html
{% extends 'root/base.html' %}
{% load cart_extras %}
{% load cart_filters %}
{% load cart_tags %}
{% block title %}Cart{% endblock %}


{% block content %}

<div class="mt-4 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Your Shopping Cart</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for cart_item in cart.items.all %}
        <div class="relative">
            <a href="{% url 'item:detail' cart_item.item.id %}">
                <img src="{{ cart_item.item.image.url }}" class="rounded-t-xl">
            
                <a href="{% url 'order:remove_from_cart' cart_item.id %}"
                    class="mr-6 mt-4 absolute right-0 px-3 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">
                    Delete
                </a>

                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ cart_item.item.name }}</h2>
                    <p class="text-gray-500 text-gray-400">Price: {{ cart_item.item.price }}</p>
                    <p class="text-gray-500 text-gray-400">Quantity: {{ cart_item.quantity }}</p>
                    
                    <form method="post" action="{% url 'order:update_item_quantity' cart_item.id %}">
                        <button type="submit" class="inline-block mt-3 px-3 py-3 text-lg font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-700">Update Quantity</button>
                        {% csrf_token %}
                        <select name="quantity" class="quantity-select">
                            {% for number in 1|to:20 %}
                            <option value="{{ number }}" {% if cart_item.quantity == number %}selected{% endif %}>{{ number }}</option>
                            {% endfor %}
                        </select>
                        
                    </form>

                    
                </div>
            </a>
        </div>
        {% empty %}
            <p>Your cart is empty.</p>
        {% endfor %}
    </div>
</div>

{% if cart.items.all %}
    <div class="cart-total mt-4 px-6" id="cart-total">
        <strong>Total:</strong> ${{ cart.items.all|cart_total }}
    </div>
    <div class="mt-4">
        <a href="{% url 'order:checkout' %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Proceed To Checkout</a>
    </div>
{% endif %}

{% endblock %}

daintree/order/templates/order/checkout.html
{% extends 'root/base.html' %}
{% block title %}Checkout{% endblock %}


{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
  <h1 class="mb-6 text-3xl" style="text-align: center;">Payment Information</h1>

  <form method="post" action=".">
      {% csrf_token %}

      <h3 class="mb-3 text-2xl">Shipping Information</h3>

      <div class="mb-3">
        <label class="inline-block mb-2" for="address">Address:</label><br>
        <input type="text" id="address" name="address" required>
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2" for="city">City:</label><br>
        <input type="text" id="city" name="city" required>
      </div>
      
      <div class="mb-3">
        <label class="inline-block mb-2" for="postcode">Postcode:</label><br>
        <input type="text" id="postcode" name="postcode" required>
      </div>


      <h3 class="mt-6 mb-3 text-2xl">Card Information</h3>

      <div class="mb-3">
        <label class="inline-block mb-2" for="card_name">Card Holder Name:</label><br>
        <input type="text" id="card_name" name="card_name" required>
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2" for="card_number">Card Number:</label><br>
        <input type="text" id="card_number" name="card_number" required>
      </div>
      
      <div class="mb-3">
        <label class="inline-block mb-2" for="expiry_date">Expiry Date:</label><br>
        <input type="text" id="expiry_date" name="expiry_date" required>
      </div>
      
      <div class="mb-3">
        <label class="inline-block mb-2" for="cvc">CVC:</label><br>
        <input type="text" id="cvc" name="cvc" required>
      </div>

      <button type="submit" class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Place Order</button>

  </form>
</div>
{% endblock %}

daintree/order/templates/order/confirmation.html
{% extends 'root/base.html' %}

{% block title %}Confirmation Page{% endblock %}

{% block content %}
    <h1 class="py-3 px-6 text-lg font-semibold bg-gray-500 text-white">Your order is confirmed </h1> <br>
    <a href="/" class="py-3 px-6 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Home</a>

{% endblock %}